# Generated by Django 4.0.5 on 2022-07-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_image', models.ImageField(upload_to='articles')),
                ('preview_image', models.ImageField(upload_to='articles')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('template', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
