# Generated by Django 4.0.5 on 2022-07-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('logo_pic', models.ImageField(upload_to='projects')),
                ('preview_pic', models.ImageField(upload_to='projects')),
                ('date', models.DateField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
