# Generated by Django 4.0.5 on 2022-07-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_tech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech',
            old_name='slug',
            new_name='template',
        ),
    ]
