# Generated by Django 4.0.5 on 2022-07-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_slug_tech_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='intro_statement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
