# Generated by Django 4.0.5 on 2022-07-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_intro_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_image',
            field=models.ImageField(default=1, upload_to='projects'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
