# Generated by Django 4.0.5 on 2022-07-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_article_slug_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='template',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
